FROM node:20.12.2-alpine
WORKDIR /app
COPY package.json package-lock.json ./
COPY server/package.json ./server/
RUN npm install --workspace=server
COPY server/ ./server/
COPY tsconfig.base.json ./
RUN npm run build -w server
EXPOSE 5000
ENV NODE_ENV=production
CMD ["node", "server/dist/server.js"]
